### PR TITLE
navigation arrow fixed for sponsor and testimonial.

### PR DESCRIPTION
**Pull request by keshav861**
this is the issue #29.
This PR resolves this issue of the navigation arrow which are not present before and now after changes it will be there which will improve the visibility and user experience.
Before:-
image
image
After:-
image
image

the issue has been resolved

### CODE REVIEW

**Comment by mlodic** [comment]
@drosetti can you plz check this?

**Review by drosetti — CHANGES_REQUESTED** [review]
Very good!
I noticed in the console there are some error logs about the elements with the same index. After you fix it i'll proceed with the merge

**Comment by keshav861** [comment]
ok i will see into the matter.

**Comment by keshav861** [comment]
> Very good! I noticed in the console there are some error logs about the elements with the same index. After you fix it i'll proceed with the merge

@drosetti I have checked that when we locally run that then it will show error because when i tried to run the website after re cloning and no updates changed on the website then also it is showing the error so i think my code is not the reason for the error same key
image
can you please check that

**Comment by drosetti** [comment]
Yes, you're right, this "problem" is not related to the code you changed, but I think this could be a good opportunity to solve this

**Comment by keshav861** [comment]
@drosetti yeah I will try to see this error too. Meanwhile you can pass my PR for this issue so this will be resolved. And I have seen that when will see on the uploaded website server where the site is uplinked there it shows no error so I was confused for it that may be possible it is due to local files the name may be common. Not on the server side you may check out.

**Comment by drosetti** [comment]
Yeah, I agree with you: the public site is not affect by this problem. I'll merge the pr

**Comment by keshav861** [comment]
@drosetti i think there is some problem with the merging of this navigation arrow code the pr is been merged but the changes are not updated in the original code. so i have again send the PR to resolve this issue. please check it and accept the PR.
the issue which was previously merged was issue https://github.com/intelowlproject/intelowlproject.github.io/pull/30

**Pull request merged**
